apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  MYSQL_HOST: "{{ .Values.mysql.host }}"
  MYSQL_PORT: "{{ .Values.mysql.port }}"
  MYSQL_USER: "{{ .Values.mysql.user }}"
  MYSQL_DATABASE: "{{ .Values.mysql.database }}"
