apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db-check
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-check
          image: mysql:8.0
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret
          command: ["/bin/sh", "-c"]
          args:
            - >
              mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD -e "SELECT 'DB connection successful' AS status;"
